name: GitHub Actions Demo
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/**'
  pull_request:
    types: [opened]
    branches:
      - main    
  workflow_dispatch: # Manual trigger      

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: name of the event
        run: echo "The event that triggered this workflow is:${{github.event_name}}"
      - name: name of the branch
        run: echo "Name of the barnch is:${{github.ref }}"
      - name: List all files
        run: |
          echo "Listing all files in the repository:"
          find .        
